version01a/issues/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from . import views

app_name = "issue"


urlpatterns = [
    # /issue/
    url(r'^$', views.Home.as_view(), name='home'),
    # /issue/add
    url(r'^add$', views.Create.as_view(), name='create'),
    # /issue/123
    url(r'^(?P<pk>[0-9]+)$', views.Detail.as_view(), name='detail'),
    # /issue/123/update
    url(r'^(?P<pk>[0-9]+)/update$', views.Update.as_view(), name='update'),
    # /issue/123/delete
    url(r'^(?P<pk>[0-9]+)/delete$', views.Delete.as_view(), name='delete'),
]

version01a/opencmis/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from . import views

app_name = "opencmis"

'''New class based system'''
urlpatterns = [
    # url(regular_expression, view, name='view_name')
    # NB. view_name is so we can refer to this URL as opencmis:view_name
    # NB. if view is a class must use views.Class.as_view() to convert it into a view

    # /opencmis/student/
    url(r'student/$',
        views.IndexView.as_view(),
        name='index'),

    # /opencmis/student/232/
    url(r'student/(?P<pk>[0-9]+)/$',
        views.StudentView.as_view(),
        name='student-detail'),

    # /opencmis/student/gmail
    url(r'student/gmail/$',
        views.gmail,
        name='gmail'),

    # /student/123/update/
    url(r'student/(?P<pk>[0-9]+)/update/$',
        views.StudentUpdate.as_view(),
        name='student-update'),

    # /student/add
    url(r'student/add/$',
        views.StudentCreate.as_view(),
        name='student-create'),

    # /student/123/delete/
    url(r'student/(?P<pk>[0-9]+)/delete/$',
        views.StudentDelete.as_view(),
        name='student-delete'),

    # STUDENT QUALIFICATIONS
    # LIST
    # /student/123/qualifications
    url(r'student/(?P<student_id>[0-9]+)/qualification/$',
        views.StudentQualificationList.as_view(),
        name='student-qualification'),

    # /student/123/qualifications/add
    url(r'student/(?P<student_id>[0-9]+)/qualification/add/$',
        views.StudentQualificationAdd.as_view(),
        name='student-qualification-create'),

    # UPDATE
    # /student/123/qualifications/123/update
    url(r'student/(?P<student_id>[0-9]+)/qualification/(?P<qualification_id>[0-9]+)/update$',
        views.StudentQualificationUpdate.as_view(),
        name='student-qualification-update'),

    # /student/123/behaviours
    url(r'student/(?P<student_id>[0-9]+)/behaviour/$',
        views.behaviour_index,
        name='behaviour-index'),

    # /student/123/baseline
    url(r'student/(?P<student_id>[0-9]+)/baseline/$',
        views.BaselineIndex.as_view(),
        name='baseline'),

    # /student/123/baseline/3/add
    url(r'student/(?P<student_id>[0-9]+)/baseline/(?P<heading>[0-9]+)/add/$',
        views.BaselineAdd.as_view(),
        name='baseline-add'),

    # /ilr/
    url(r'ilr/$', views.ILR, name='ilr'),

    # /dashboard/
    url(r'dashboard/$', views.dashboard, name='dashboard'),

    # /import_users/
    url(r'import_users/$', views.import_users, name='import-users'),
]

version01a/version01a/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^opencmis/', include('opencmis.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^article/', include('articles.urls')),
    url(r'^issue/', include('issues.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

version01a/issues/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class Issue(models.Model):
    title = models.CharField(max_length=120, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    summary = models.TextField()
    PRIORITY_CHOICES = (('H', 'High'), ('M', 'Medium'), ('L', 'Low'))
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default='M')
    SPEED_CHOICES = (('Q', 'Quick'), ('M', 'Medium'), ('S', 'Slow'))
    speed = models.CharField(max_length=1, choices=SPEED_CHOICES, default='M')
    STATUS_CHOICES = (('O', 'Open'), ('C', 'Closed'), ('H', 'On hold'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='O')
    creation_time = models.DateTimeField(default=timezone.now)
    response_time = models.DateTimeField(null=True, blank=True)
    complete_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('issue:detail', kwargs={'pk': str(self.pk)})


class Update(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    public = models.BooleanField(default=True)
    date = models.DateTimeField(default=timezone.now)
    personnel = models.ForeignKey(User, on_delete=models.CASCADE)
    update = models.TextField()

    def __str__(self):
        return '{0} {1}'.format(self.date, self.personnel)

    def get_absolute_url(self):
        # Default page is details page of the parent issue
        return reverse('issue:detail', kwargs={'pk': str(self.issue)})

    def save(self, *args, **kwargs):
        # TODO: Investigate save method as the place to do logging
        # Do something before saving
        super(Update, self).save(*args, **kwargs)
        # Do something after saving

version01a/issues/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User
from .models import Issue, Update as My_Update


class Home(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Issue
    template_name = 'issue/home.html'
    queryset = Issue.objects.all()

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


# class Detail(LoginRequiredMixin, DetailView):
class Detail(LoginRequiredMixin, UpdateView):
    # PAB 02/12/2016 Renamed this to old so I can start a new class called Detail
    # based on the FormView
    # PAB 02/12/2016
    # I originally used just a DetailView which works fine for output only forms
    # but this form is a bit different because I also want to do some input, i.e. I want to POST update data to it.
    # I changed from a DetailView to an UpdateView and tried to work with the Post functions but it still doesn't work.
    # I wonder whether I should just bite the bullet and make my own FormView.
    # This appears to allow me to do anything with forms whereas the predefined Views are specifically limited to
    # certain situations.

    login_url = reverse_lazy('login')
    model = Issue
    template_name = 'issue/detail.html'
    fields = '__all__'  # Needed to add this in if changing from DetailView to UpdateView

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['updates'] = My_Update.objects.filter(issue=self.kwargs['pk'])
        context['index'] = index_context(self.request)
        return context

    def form_valid(self, form):
        # TODO: This never seems to get called
        print("Hello world")
        print(form)
        return super(Detail, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        This is only called when a user Clicks the Update button and the update form is submitted.
        If the page is called via a GET command this is not called.
        :param request: Use request.POST to get the form data from the Update section
        :param args:
        :param kwargs: Use kwargs['pk'] to get the issue id from the URL
        :return:
        """
        # TODO: Do we need two forms here; one for issue record and one for update record?
        if request.method == 'POST':
            # Work out which form was posted, note that accessing a non existent form element raises an exception
            form = "None"  # Just a starting value
            try:
                print(request.POST['Status'])
                if request.POST['Status']:
                    form = "Issue"
            except MultiValueDictKeyError:
                pass

            try:
                print(request.POST['Public'])
                if request.POST['Public']:
                    form = "Comment"
            except MultiValueDictKeyError:
                pass

            if form == "Issue":
                q = Issue.objects.get(pk=kwargs['pk'])
                print(request.POST['Status'])
                if request.POST['Status'] == "Open":
                    q.status = "O"
                elif request.POST['Status'] == "Close":
                    q.status = "C"
                elif request.POST['Status'] == "On hold":
                    q.status = "H"
                print("make is so {0}".format(q.status))
                q.save()
            elif form == "Comment":
                # TODO: Doing forms this way bypasses validation
                # Validate Public field, only Public or Private fields allowed
                if request.POST['Public'] == 'Public':
                    public_boolean = True
                elif request.POST['Public'] == 'Private':
                    public_boolean = False

                q = My_Update(issue=Issue.objects.get(pk=kwargs['pk']),
                              date=timezone.now(),
                              personnel=User.objects.get(username=request.user.username),
                              update=request.POST['Update'],
                              public=public_boolean)
                print(q.public)
                q.save()

        return HttpResponseRedirect('/issue/{0}'.format(kwargs['pk']))


class Create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.create_issue'
    model = Issue
    template_name = 'issue/issue-form.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(Create, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


class Update(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.change_issue'
    model = Issue
    template_name = 'issue/issue-form.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(Update, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


class Delete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.delete_issue'
    model = Issue
    success_url = reverse_lazy('issue:home')

    def get_context_data(self, **kwargs):
        context = super(Delete, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


def index_context(request):
    """index filtering and search"""
    # Check to see if index is limited via filter
    f = request.GET.get('filter')
    if f and f != "Any":
        index = Issue.objects.filter(status=f)
    else:
        index = Issue.objects.all()
    # Check to see if index is limited via search
    query = request.GET.get('q')
    if query:
        query_list = query.split()
        if len(query_list) == 1:
            print("Query_list = {0}".format(query_list))
            index = index.filter(Q(title__contains=query_list[0]) or Q(summary__contains=query_list[0]))
    paginator = Paginator(index, 20)  # Limit to 20 entries per page, then paginate
    page = request.GET.get('page')
    try:
        index = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        index = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        index = paginator.page(paginator.num_pages)
    # Now we've finished refining index simply pass it to the context dictionary
    return index

version01a/opencmis/templates/issue/detail.html
{% extends 'issue/issue-base.html' %}
{% block title %}Issue{% endblock %}
{% block baseline-active %}active{% endblock %}
{% block body %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">{{object.title}}</h3>
    </div>
    <div class="panel-body">{{object.summary|striptags|urlize|linebreaks}}
        <ul class="list-group">
        {% for update in updates %}
            <li class="list-group-item {% if not update.public %}list-group-item-warning{% endif %}">
                <p>{{update.date|date:"d/m/Y"}}  {{update.personnel}}
                {{update.update|striptags|urlize|linebreaks}}
            </li>
        {% empty %}
            <p>There are no updates yet.</p>
        {% endfor %}
        </ul>
    </div>

    <div class="panel-footer hidden-print">
        <form class="form-horizontal" action="" method="post" id="Ticket">
            {% csrf_token %}
            <div class="form-check">
                <label>Status:</label>
                <label class="radio-inline">
                    <input type="radio" onChange='this.form.submit();' name="Status" value="Close" {% ifequal object.status "C" %}checked="checked"{% endifequal %}>Close</label>
                <label class="radio-inline">
                    {% ifequal object.status "C" %}
                    <input type="radio" onChange='this.form.submit();' name="Status" value="Open" {% ifequal object.status  "O" %}checked="checked"{% endifequal %}>Re open</label>
                    {% else %}
                    <input type="radio" onChange='this.form.submit();' name="Status" value="Open" {% ifequal object.status  "O" %}checked="checked"{% endifequal %}>Open</label>
                    {% endifequal %}
                <label class="radio-inline">
                    <input type="radio" onChange='this.form.submit();' name="Status" value="On hold" {% ifequal object.status  "H" %}checked="checked"{% endifequal %}>On hold</label>
            </div>
        </form>
        <form class="form-horizontal" action="" method="post" id="Comment">
            {% csrf_token %}
            <div class="form-check">
                <label>Public:</label>
                <!-- TODO: Public / Private doesn't work -->
                <label class="radio-inline"><input type="radio" name="Public"  value="Public" checked>Public</label>
                <label class="radio-inline"><input type="radio" name="Public" value="Private">Private</label>
            </div>
            <div class="form-check">
                <!--TODO: This bit doesn't actually work-->
                <label for="update">Update:</label>
                <textarea class="form-control" rows="5" id="update" name="Update" placeholder="Type Something here"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
{% comment %}
Notice the user of perm here, especially perm.appname.permision
Can use this to check whether editable links should be displayed or not
{% endcomment %}
<!-- TODO: Just avoid errors at the moment fix later-->
{%comment%}
<div class="hidden-print">
{% if perms.issue.change_issue %}
    <a href="{% url 'issue:update' object.id %}">Edit</a><br>
{% endif %}
{% if perms.issue.delete_issue %}
    <a href="{% url 'issue:delete' object.id %}">Delete</a><br>
{%endif %}
</div>
{%endcomment%}
{% endblock %}}

version01a/opencmis/templates/issue/form.html
{{form.as_p}}

version01a/opencmis/templates/issue/home.html
{% extends 'issue/issue-base.html' %}
{% block title %}Issue Index{% endblock %}
{% block home-active %}active{% endblock %}

{% block body %}
<h1>Issues</h1>
<p>I should show the state of affairs here.</p>
<p>Some KPIs showing non triaged issues, overdue issues, high priority, easy fixes, etc. .</p>
{% endblock %}

version01a/opencmis/templates/issue/issue-base.html
{% extends 'opencmis/base.html' %}
{% block index %}
<div class="hidden-print">
    <!-- Add new issue -->
    {% if perms.add_issue %}
        <a href="{% url 'issue:create' %}">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;New Issue
        </a>
        <hr>
    {% endif %}
    <!-- Search form -->
    <form id="searchform" action="" method="get" accept-charset="utf-8">
        <fieldset>
            <div class="form-group">
                <label class="col-xs-4 col-form-label" for="filter">Status</label>
                <div class="col-xs-8">
                    <select class="form-control" id = "filter" name="filter">
                        <option value="Any">Any</option>
                        <option value="O">Open</option>
                        <option value="C">Closed</option>
                        <option value="H">On Hold</option>
                    </select>
                </div>

                <input class="form-control" id="searchbox" name="q" type="text" placeholder="Search">
                <button class="btn btn-primary" type="submit">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>

            </div>
        </fieldset>
    </form>
    <hr>
    <!-- Index -->
    {% for i in index %}
        <a href="{% url 'issue:detail' i.id %}">{{i}}</a><br>
    {% empty %}
        <li>What? No issues?</li>
    {% endfor %}
    <!-- Pagination -->
    {% if index.paginator.num_pages != 1 %}
    <div class="pagination">
        <span class="step-links">
            {% if index.has_previous %}
                <a href="?page=1">
                    <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                </a>
                <a href="?page={{ index.previous_page_number }}">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>
            {% else %}
                <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            {% endif %}

            <span class="current">
                [ {{ index.number }} / {{ index.paginator.num_pages }} ]
            </span>

            {% if index.has_next %}
                <a href="?page={{ index.next_page_number }}">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </a>
                <a href="?page={{ index.paginator.num_pages }}">
                    <span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
                </a>
            {% else %}
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
            {% endif %}
        </span>
        <div id=”results”></div>
    </div>
    {% endif %}
    </div>
{% endblock %}

version01a/opencmis/templates/issue/issue-form.html
{% extends 'issue/issue-base.html' %}
{% block title %}Add Issue{% endblock %}
{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'issue/form.html' %}
        <div class="form-group">
            <button class="btn btn-default" type="submit">Submit</button>
        </div>
        </div>
    </form>
{% endblock %}