version01a/issues/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from . import views

app_name = "issue"


urlpatterns = [
    # /issue/
    url(r'^$', views.Home.as_view(), name='home'),
    # /issue/add
    url(r'^add$', views.Create.as_view(), name='create'),
    # /issue/123
    url(r'^(?P<pk>[0-9]+)$', views.Detail.as_view(), name='detail'),
    # /issue/123/update
    url(r'^(?P<pk>[0-9]+)/update$', views.Update.as_view(), name='update'),
    # /issue/123/delete
    url(r'^(?P<pk>[0-9]+)/delete$', views.Delete.as_view(), name='delete'),
]

version01a/opencmis/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from . import views

app_name = "opencmis"

'''New class based system'''
urlpatterns = [
    # url(regular_expression, view, name='view_name')
    # NB. view_name is so we can refer to this URL as opencmis:view_name
    # NB. if view is a class must use views.Class.as_view() to convert it into a view

    # /opencmis/student/
    url(r'student/$',
        views.IndexView.as_view(),
        name='index'),

    # /opencmis/student/232/
    url(r'student/(?P<pk>[0-9]+)/$',
        views.StudentView.as_view(),
        name='student-detail'),

    # /opencmis/student/gmail
    url(r'student/gmail/$',
        views.gmail,
        name='gmail'),

    # /student/123/update/
    url(r'student/(?P<pk>[0-9]+)/update/$',
        views.StudentUpdate.as_view(),
        name='student-update'),

    # /student/add
    url(r'student/add/$',
        views.StudentCreate.as_view(),
        name='student-create'),

    # /student/123/delete/
    url(r'student/(?P<pk>[0-9]+)/delete/$',
        views.StudentDelete.as_view(),
        name='student-delete'),

    # STUDENT QUALIFICATIONS
    # LIST
    # /student/123/qualifications
    url(r'student/(?P<student_id>[0-9]+)/qualification/$',
        views.StudentQualificationList.as_view(),
        name='student-qualification'),

    # /student/123/qualifications/add
    url(r'student/(?P<student_id>[0-9]+)/qualification/add/$',
        views.StudentQualificationAdd.as_view(),
        name='student-qualification-create'),

    # UPDATE
    # /student/123/qualifications/123/update
    url(r'student/(?P<student_id>[0-9]+)/qualification/(?P<qualification_id>[0-9]+)/update$',
        views.StudentQualificationUpdate.as_view(),
        name='student-qualification-update'),

    # /student/123/behaviours
    url(r'student/(?P<student_id>[0-9]+)/behaviour/$',
        views.behaviour_index,
        name='behaviour-index'),

    # /student/123/baseline
    url(r'student/(?P<student_id>[0-9]+)/baseline/$',
        views.BaselineIndex.as_view(),
        name='baseline'),

    # /student/123/baseline/3/add
    url(r'student/(?P<student_id>[0-9]+)/baseline/(?P<heading>[0-9]+)/add/$',
        views.BaselineAdd.as_view(),
        name='baseline-add'),

    # /ilr/
    url(r'ilr/$', views.ILR, name='ilr'),

    # /dashboard/
    url(r'dashboard/$', views.dashboard, name='dashboard'),

    # /import_users/
    url(r'import_users/$', views.import_users, name='import-users'),
]

version01a/version01a/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^opencmis/', include('opencmis.urls')),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^article/', include('articles.urls')),
    url(r'^issue/', include('issues.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

version01a/opencmis/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


class Student(models.Model):
    status = models.ForeignKey('Status', blank=False)
    title = models.ForeignKey('Title', blank=True)
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    ethnicity = models.ForeignKey('Ethnicity', blank=True, null=True, on_delete=models.SET_NULL)
    date_of_birth = models.DateField(blank=False)
    ULN = models.CharField(max_length=10, blank=True,
                           validators=[RegexValidator(regex=r'^[1-9][0-9]{9}$',
                                                      message='ULN must be 1000000000 to 9999999999',
                                                      code='invalid_uln')])
    house = models.CharField(max_length=50, blank=True)
    road = models.CharField(max_length=50, blank=True)
    area = models.CharField(max_length=50, blank=True)
    town = models.CharField(max_length=50, blank=True)
    post_code = models.CharField(max_length=12, blank=True)
    photo = models.FileField(blank=True)

    def __str__(self):
        """ return name of an individual object """
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        """
        Return url of an individual object.
        This is used as a follow up address after an editing view has been submitted
         """
        # Although the manual says do it like below it doesn't actually work on my project
        # return reverse('opencmis.views.detail', args=[str(self.id)])
        return u'/opencmis/student/%d' % self.id

    class Meta:
        permissions = (
            ("view_student", "Can see students"),
        )


class StudentExtras(models.Model):
    student = models.OneToOneField('Student', on_delete=models.CASCADE, primary_key=True)
    NI_number = models.CharField(max_length=12)
    Sexuality = models.CharField(max_length=20, default='Heterosexual')

    def __str__(self):
        return self.student


class Behaviour(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    issue = models.TextField(max_length=50, blank=False)
    action = models.TextField(max_length=50)

    def __str__(self):
        return self.issue


class Teacher(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    role = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Qualification(models.Model):
    title = models.CharField(max_length=100, blank=False)
    LAR = models.CharField(max_length=12, blank=False)

    def __str__(self):
        return '%s: %s' % (self.LAR, self.title)


class StudentQualification(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    qualification = models.ForeignKey('Qualification', on_delete=models.CASCADE)
    start = models.DateField(blank=False)
    expected_end = models.DateField(blank=False)

    def __str__(self):
        return '%s: %s' % (self.student, self.qualification)

    def get_absolute_url(self):
        return u'/opencmis/student/{0}/qualification/'.format(self.student_id)


class BaselineEntry(models.Model):
    """ The database has text entries for all the data from Debbie and Nicola's word document """
    heading = models.CharField(max_length=80)
    blurb = models.TextField()

    def __str__(self):
        return "%s" % self.heading

    class Meta:
        verbose_name_plural = 'BaselineEntries'


class BaselineValue(models.Model):
    """ Every baseline entry will have one of these"""
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    baseline = models.ForeignKey(BaselineEntry, on_delete=models.CASCADE)
    WEEKS_CHOICES = ((1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'))
    week = models.IntegerField(choices=WEEKS_CHOICES, default=1)
    text = models.TextField()
    # date - future maybe
    # user - future maybe

    def __str__(self):
        return "{0} {1} {2}".format(self.student, self.baseline, self.week)

    def get_absolute_url(self):
        return u'/opencmis/student/{0}/baseline/'.format(self.student_id)


class Building(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name


class Room(models.Model):
    building = models.ForeignKey('Building', on_delete=models.CASCADE)
    room = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return '%s: %s' % (self.building, self.name)


class Staff(models.Model):
    """This is an example of how to make the plural of a class name
    When adding an s simply doesn't cut it."""
    class Meta:
        verbose_name_plural = 'Staff'

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)


class Ethnicity(models.Model):
    value = models.CharField(max_length=80)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name_plural = 'Ethnicities'


class Status(models.Model):
    status = models.CharField(max_length=80)

    class Meta:
        verbose_name_plural = 'Status'

    def __str__(self):
        return self.status


class Title(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


# Classes for ILR
# TODO: Fix me! This works but it isn't right.  Specific data for an installation shouldn't be in the code it should be
# in the database and have a specific form.


class Organisation(models.Model):
    ukprn = models.CharField(max_length=8, unique=True)  # 10002006
    name = models.CharField(max_length=100)  # 'Communication Specialist College Doncaster"
    post_code = models.CharField(max_length=10)


class Header:
    """
    # TODO: Make this into a table of globals , i.e. tag, value.
    Note this isn't a models.Model it is just a class to enable me to define some one off values for the ILR.
    """
    UKPRN = '10002006'
    post_code = 'DN2 6AY'

version01a/issues/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User
from .models import Issue, Update as My_Update


class Home(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Issue
    template_name = 'issue/home.html'
    queryset = Issue.objects.all()

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


# class Detail(LoginRequiredMixin, DetailView):
class Detail(LoginRequiredMixin, UpdateView):
    # PAB 02/12/2016 Renamed this to old so I can start a new class called Detail
    # based on the FormView
    # PAB 02/12/2016
    # I originally used just a DetailView which works fine for output only forms
    # but this form is a bit different because I also want to do some input, i.e. I want to POST update data to it.
    # I changed from a DetailView to an UpdateView and tried to work with the Post functions but it still doesn't work.
    # I wonder whether I should just bite the bullet and make my own FormView.
    # This appears to allow me to do anything with forms whereas the predefined Views are specifically limited to
    # certain situations.

    login_url = reverse_lazy('login')
    model = Issue
    template_name = 'issue/detail.html'
    fields = '__all__'  # Needed to add this in if changing from DetailView to UpdateView

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['updates'] = My_Update.objects.filter(issue=self.kwargs['pk'])
        context['index'] = index_context(self.request)
        return context

    def form_valid(self, form):
        # TODO: This never seems to get called
        print("Hello world")
        print(form)
        return super(Detail, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        This is only called when a user Clicks the Update button and the update form is submitted.
        If the page is called via a GET command this is not called.
        :param request: Use request.POST to get the form data from the Update section
        :param args:
        :param kwargs: Use kwargs['pk'] to get the issue id from the URL
        :return:
        """
        # TODO: Do we need two forms here; one for issue record and one for update record?
        if request.method == 'POST':
            # Work out which form was posted, note that accessing a non existent form element raises an exception
            form = "None"  # Just a starting value
            try:
                print(request.POST['Status'])
                if request.POST['Status']:
                    form = "Issue"
            except MultiValueDictKeyError:
                pass

            try:
                print(request.POST['Public'])
                if request.POST['Public']:
                    form = "Comment"
            except MultiValueDictKeyError:
                pass

            if form == "Issue":
                q = Issue.objects.get(pk=kwargs['pk'])
                print(request.POST['Status'])
                if request.POST['Status'] == "Open":
                    q.status = "O"
                elif request.POST['Status'] == "Close":
                    q.status = "C"
                elif request.POST['Status'] == "On hold":
                    q.status = "H"
                print("make is so {0}".format(q.status))
                q.save()
            elif form == "Comment":
                # TODO: Doing forms this way bypasses validation
                # Validate Public field, only Public or Private fields allowed
                if request.POST['Public'] == 'Public':
                    public_boolean = True
                elif request.POST['Public'] == 'Private':
                    public_boolean = False

                q = My_Update(issue=Issue.objects.get(pk=kwargs['pk']),
                              date=timezone.now(),
                              personnel=User.objects.get(username=request.user.username),
                              update=request.POST['Update'],
                              public=public_boolean)
                print(q.public)
                q.save()

        return HttpResponseRedirect('/issue/{0}'.format(kwargs['pk']))


class Create(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.create_issue'
    model = Issue
    template_name = 'issue/issue-form.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(Create, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


class Update(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.change_issue'
    model = Issue
    template_name = 'issue/issue-form.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(Update, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


class Delete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'issue.delete_issue'
    model = Issue
    success_url = reverse_lazy('issue:home')

    def get_context_data(self, **kwargs):
        context = super(Delete, self).get_context_data(**kwargs)
        context['index'] = index_context(self.request)
        return context


def index_context(request):
    """index filtering and search"""
    # Check to see if index is limited via filter
    f = request.GET.get('filter')
    if f and f != "Any":
        index = Issue.objects.filter(status=f)
    else:
        index = Issue.objects.all()
    # Check to see if index is limited via search
    query = request.GET.get('q')
    if query:
        query_list = query.split()
        if len(query_list) == 1:
            print("Query_list = {0}".format(query_list))
            index = index.filter(Q(title__contains=query_list[0]) or Q(summary__contains=query_list[0]))
    paginator = Paginator(index, 20)  # Limit to 20 entries per page, then paginate
    page = request.GET.get('page')
    try:
        index = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        index = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        index = paginator.page(paginator.num_pages)
    # Now we've finished refining index simply pass it to the context dictionary
    return index

version01a/opencmis/templates/opencmis/baseline-add.html
{% extends 'opencmis/student-base.html' %}
{% block title %}{{ student}}{% endblock %}
{% block baseline-active %}active{% endblock %}
{% block student-body %}
    {% for e in baseline_list %}
        <div class="panel panel-default">
            <div class="panel-heading">{{e.entry}}</div>
            <div class="panel-body">
                {% for i in e.data %}
                <div class="panel panel-default">
                    <div class="panel-heading">Week&nbsp;{{i.week}}&nbsp;<a href="{% url 'opencmis:student-update' student.id %}"><span
                    class="glyphicon glyphicon-pencil"></span></a></div>
                    <div class="panel-body">
                        <!-- |add:"0" forces a string to int.-->
                        <!-- |add:"0" simply adds 0 if it is already an int -->
                        {% if e.entry.id|add:"0" == header|add:"0" %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="comment">Comment:</label>
                                <textarea class="form-control" rows="4" cols="50" id="comment"></textarea>
                            </div>
                            <button type="button" class="btn btn-primary">Save</button>
                        </form>
                        {% else %}
                            {{i.text|linebreaks}}
                        {% endif %}

                    </div>
                    <div class="panel-footer">{{i.user}} : {{i.date}} - {{header}}</div>
                </div>
                {% empty %}
                    <div class="alert alert-warning" role="alert">
                        <strong>There are no records to display.</strong>
                    </div>
                {% endfor %}
                <a href="{% url 'opencmis:baseline-add' student.id e.entry.pk %}">

                    <span class="glyphicon glyphicon-plus"></span>
                </a>
            </div>
        </div>
    {% empty %}
        <div class="alert alert-warning" role="alert">
            <strong>There are no qualifications to display.</strong>
        </div>
    {% endfor %}
{% endblock %}

version01a/opencmis/templates/opencmis/baseline.html
{% extends 'opencmis/student-base.html' %}
{% block title %}{{ student}}{% endblock %}
{% block baseline-active %}active{% endblock %}
{% block student-body %}
    {% for e in baseline_list %}
        <div class="panel panel-default">
            <div class="panel-heading"><h3>{{e.entry.heading}}</h3>{{e.entry.blurb|linebreaks}}</div>

            <div class="panel-body">
                {% for i in e.data %}
                <div class="panel panel-default">
                    <div class="panel-heading">Week&nbsp;{{i.week}}&nbsp;<a href="{% url 'opencmis:student-update' student.id %}"><span
                    class="glyphicon glyphicon-pencil"></span></a></div>
                    <div class="panel-body">
                        {{i.text|safe}}
                    </div>
                    <div class="panel-footer">{{i.user}} : {{i.date}}</div>
                </div>
                {% empty %}
                    <div class="alert alert-warning" role="alert">
                        <strong>There are no records to display.</strong>
                    </div>
                {% endfor %}
                <a href="{% url 'opencmis:baseline-add' student.id e.entry.pk %}">

                    <span class="glyphicon glyphicon-plus"></span>
                </a>
            </div>
        </div>
    {% empty %}
        <div class="alert alert-warning" role="alert">
            <strong>There are no baselines to display.</strong>
        </div>
    {% endfor %}
{% endblock %}

version01a/opencmis/templates/opencmis/behaviour_index.html
{% extends 'opencmis/student-base.html' %}
{% block title %}{{ student}}{% endblock %}
{% block behaviour-active %}active{% endblock %}
{% block student-body %}
    {% for item in behaviour_list %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-10">{{item.issue}}</div><div class="col-md-2">Date</div>
            </div>
        </div>
    {% empty %}
        <div class="alert alert-warning">There are no issues for this student.</div>
    {% endfor %}
{% endblock %}

version01a/opencmis/templates/opencmis/detail.html
{% extends 'opencmis/student-base.html' %}
{% block title %}{{student}}{% endblock %}
{% block home-active %}active{% endblock %}
{% block student-body %}
    <div class="row">
        <div class="col-md-4">
            {% if student.photo %}
            <img src="{{student.photo.url }}" class="img-responsive">
            {% else %}
            <div class="alert alert-warning" role="alert">
                <strong>No photo</strong>
            </div>
            {% endif %}
        </div>
        <div class="col-md-8"></div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% if perms.opencmis.change_student %}
            <a href="{% url 'opencmis:student-update' student.id %}">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            {% endif %}
            {% if perms.opencmis.delete_student %}
            <a href="{% url 'opencmis:student-delete' student.id %}">
                <span class="glyphicon glyphicon-remove-circle"></span>
            </a>
            {% endif %}
            {% if student.title.title != "Unknown" %}
                {{student.title}}&nbsp;
            {% endif %}
            {{student.first_name}}&nbsp;{{student.last_name}}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">Status:</div>
        <div class="col-md-10">{{student.status.status}}</div>
    </div>
    <div class="row">
        <div class="col-md-2">Date of Birth:</div>
        <div class="col-md-10">{{student.date_of_birth}}</div>
    </div>
    <div class="row">
        <div class="col-md-2">Gender:</div>
        <div class="col-md-10">{{student.gender}}</div>
    </div>
    <div class="row">
        <div class="col-md-2">Ethnicity:</div>
        <div class="col-md-10">{{student.ethnicity}}</div>
    </div>
    <div class="row">
        <div class="col-md-2">ULN:</div>
        <div class="col-md-10">{{student.ULN}}</div>
    </div>
    <div class="row">
        <div class="col-md-2">House</div>
        <div class="col-md-10">{{student.house}}</div>
    </div>

    <div class="row">
        <div class="col-md-12">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
{% endblock %}

version01a/opencmis/templates/opencmis/form-template.html
{% load templates %}
{% for field in form %}
    {% comment %}
    Try to use as much Bootstrap formatting as is possible
    But {{field}} autogens controls making it difficult to add classes
    Solved by using add_css templatetag
    {% endcomment %}
    <div class="form-group">
        <span class="text-danger small">{{ field.errors }}</span>
        <label class="control-label" for="{{field.id_for_label}}">
            {{ field.label }}
        </label>
        {{ field|add_css:"form-control" }}
    </div>
{% endfor %}

version01a/opencmis/templates/opencmis/index.html
{% extends 'opencmis/student-base.html' %}
{% block title %}Student Index{% endblock %}
{% block home-active %}active{% endblock %}

{% block body %}
<div class="panel panel-primary">
<div class="panel-heading">Welcome to OpenCMIS.</div>
<div class="panel-body">The Open Source College Management Information System.<br>
Written by Patrick Biggs.<br>
    <pre><kbd>Type this in, i.e. keyboard entry</kbd></pre>
    <pre><code>code goes here</code></pre>
    <samp>This is your output</samp>
    <var>x</var> = <var>y/2</var>
</div>

</div>
{% endblock %}

version01a/opencmis/templates/opencmis/qualification_index.html
{% extends 'opencmis/student-base.html' %}
{% block title %}{{student}}{% endblock %}
{% block qualification-active %}active{% endblock %}
{% block student-body %}
    {% for qual in qual_list %}
        <div class="row">
            <div class="col-md-6">{{qual.qualification}}</div>
            <div class="col-md-2">{{qual.start}}</div>
            <div class="col-md-2">{{qual.expected_end}}</div>
            {% if perms.opencmis.change_qualification %}
            <a href="{% url 'opencmis:student-qualification-update' student.id qual.id %}"><span
                    class="glyphicon glyphicon-pencil" area-hidden="true"></span>&nbsp;Edit</a>
            {% endif %}
        </div>
    {% empty %}
        <div class="alert alert-warning" role="alert">
            <strong>There are no qualifications to display.</strong>
        </div>
    {% endfor %}
    {% if perms.opencmis.add_qualification %}
    <div class="row">
            <a href="{% url 'opencmis:student-qualification-create' student.id %}">
                <span class="glyphicon glyphicon-plus-sign" area-hidden="true"></span>
                &nbsp;&nbsp;Add Qualification
            </a>
    </div>
    {% endif %}
{% endblock %}

version01a/opencmis/templates/opencmis/student-base.html
{% extends 'opencmis/base.html' %}
{% block submenu %}
<!-- Submenu fails if student doesn't contain a valid id -->
<!-- Set student to Nobody on index page when a student hasn't yet been selected -->
<!-- Check if there is a selected student before trying to access student ids -->
{% if student != 'Nobody' %}
<ul class="nav nav-tabs">
    <li class="{% block home-active %}{% endblock %}"><a href="{% url 'opencmis:student-detail' student.id %}">Home</a></li>
    <li class="{% block baseline-active %}{% endblock %}"><a href="{% url 'opencmis:baseline' student.id %}">Baseline Assessment</a></li>
    <li class="{% block target-active %}{% endblock %}"><a href="#">Targets</a></li>
    <li class="{% block qualification-active %}{% endblock %}"><a href="{% url 'opencmis:student-qualification' student.id %}">Qualifications</a></li>
    <li class="{% block review-active %}{% endblock %}"><a href="#">Reviews</a></li>
    <li class="{% block audiology-active %}{% endblock %}"><a href="#">Audiology</a></li>
    <li class="{% block medical-active %}{% endblock %}"><a href="#">Medical</a></li>
    <li class="{% block behaviour-active %}{% endblock %}"><a href="{% url 'opencmis:behaviour-index' student.id %}">Behaviour</a></li>
</ul>
{% endif %}
{% endblock %}
{% block body %}
<div class="panel panel-primary">
    <div class="panel-heading">{{student}}</div>
    <div class="panel-body">
        {% block student-body %}
        {% endblock %}
    </div>
</div>
{% endblock %}
{% block index %}
    <!--TODO: Best Practice Expand this across all applications-->
    {% if perms.add_student %}
    <a href="{% url 'opencmis:student-create' %}">
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
    </a>
    {% endif %}

    <form id="searchform" action="" method="get" accept-charset="utf-8">
        <fieldset>
            <div class="form-group">
                <label class="col-xs-4 col-form-label" for="filter">Status</label>
                <div class="col-xs-8">
                    <select class="form-control" id = "filter" name="filter">
                        <option value="any">Any</option>
                        {% for v in index.filter %}
                        <option value="{{v.id}}">{{v}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-xs-10">
                    <input class="form-control" id="searchbox" name="q" type="text" placeholder="Search">
                </div>
                <div class="col-xs-2">
                    <button class="btn btn-primary" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
    {% for i in index.index %}
    <a href="{% url 'opencmis:student-detail' i.id %}">{{i}}</a><br>
    {% empty %}
    <li>No people returned.</li>
    {% endfor %}
    <!-- TODO: Best Practice Do long indices like this -->
    {% if index.index.paginator.num_pages != 1 %}
    <div class="pagination">
        <span class="step-links">
            {% if index.index.has_previous %}
                <a href="?page=1">
                    <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                </a>
                <a href="?page={{ index.index.previous_page_number }}">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>
            {% else %}
                <span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            {% endif %}

            <span class="current">
                [ {{ index.index.number }} / {{ index.index.paginator.num_pages }} ]
            </span>

            {% if index.index.has_next %}
                <a href="?page={{ index.index.next_page_number }}">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </a>
                <a href="?page={{ index.index.paginator.num_pages }}">
                    <span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
                </a>
            {% else %}
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
            {% endif %}
        </span>
        <div id=”results”></div>
    </div>
    {% endif %}
{% endblock %}